stages:
  - build
  - test

make_env:
  stage: build
  image: python:3.8-slim-bullseye
  script:
    - apt-get update && apt-get install -y wget
    - pip install --upgrade pip
    - pip install -r requirements.txt
  artifacts:
    untracked: true

prepare_data_inputs_test:
  stage: test
  image: python:3.8-slim-bullseye
  script:
    - wget http://www-hep.colorado.edu/~nzipper/cicd_files/test_data_ntuple.root
    - python prepare_data_inputs.py -m split -o . -i data/test_data_ntuple.root
  artifacts:
    paths:
      - output/
