stages:
  - codechecks
  - prepare_inputs
  - train
  - measure

typecheck:
  stage: codechecks
  image: python:3.8-slim-bullseye
  before_script:
    - pip install --upgrade pip && pip install -r requirements.txt && pip install mypy
  script:
    - mypy --install-types .
  allow_failure: true

prepare_data_inputs:
  stage: prepare_inputs
  image: python:3.8-slim-bullseye
  before_script:
    - apt-get update && apt-get install -y wget
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - wget http://www-hep.colorado.edu/~nzipper/cicd_files/test_data_ntuple.root
    - mkdir outputs
  script:
    - python prepare_data_inputs.py -m split -o ./outputs -i test_data_ntuple.root -l cicd
  artifacts:
    paths:
      - outputs/

prepare_mc_inputs:
  stage: prepare_inputs
  image: rootproject/root:latest
  before_script:
    - apt-get update && apt-get install -y -qq wget && apt-get install -y -qq pip
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - wget http://www-hep.colorado.edu/~nzipper/cicd_files/test_mc_ntuple.root
    - mkdir outputs
  script:
    - python prepare_mc_inputs.py -m split -o ./outputs -i test_mc_ntuple.root -l cicd
  artifacts:
    paths:
      - outputs/

train_test:
  stage: train
  image: python:3.8-slim-bullseye
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python train_bdt.py --modelname cicd_test --sigfile ./outputs/trainSgn_bdt_KEE_PFe_lowQ_cicd.root --bkgfile ./outputs/trainBkg_bdt_sideBands_lowQ_cicd.root --outdir ./outputs --ntree 100 --no_plot
  artifacts:
    paths:
      - outputs/

measure_test:
  stage: measure
  image: python:3.8-slim-bullseye
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python measure_bdt.py  --fromdir ./outputs/cicd_test --measurefile ./outputs/measurement_bdt_cicd.root
  artifacts:
    paths:
      - outputs/
