stages:
  - codechecks
  - prepare_inputs
  - train
  - measure

mypy_typecheck:
  stage: codechecks
  image: python:3.8-slim-bullseye
  before_script:
    - pip install --upgrade pip && pip install -r requirements.txt && pip install mypy
  script:
    - mypy .
  allow_failure: true

ruff_linting:
  stage: codechecks
  image: registry.gitlab.com/pipeline-components/ruff:latest
  script:
    - ruff check --output-format gitlab --ignore E501,E701 .
  allow_failure: true

prepare_data_inputs:
  stage: prepare_inputs
  image: python:3.8-slim-bullseye
  before_script:
    - apt-get update && apt-get install -y wget
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - wget http://www-hep.colorado.edu/~nzipper/cicd_files/test_data_ntuple_flat.root
    - mkdir outputs
  script:
    - python prepare_inputs.py -m split -o ./outputs -i test_data_ntuple_flat.root -l cicd -f -c data
  artifacts:
    paths:
      - outputs/

prepare_mc_inputs:
  stage: prepare_inputs
  image: rootproject/root:latest
  before_script:
    - apt-get update && apt-get install -y -qq wget && apt-get install -y -qq pip
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - wget http://www-hep.colorado.edu/~nzipper/cicd_files/test_mc_ntuple_flat.root
    - mkdir outputs
  script:
    - python prepare_inputs.py -m split -o ./outputs -i test_mc_ntuple_flat.root -l cicd -f -c rare
  artifacts:
    paths:
      - outputs/

train_test:
  stage: train
  image: python:3.8-slim-bullseye
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python train_bdt.py --modelname cicd_test --sigfile ./outputs/train_sig_rare_lowQ_cicd.root --bkgfile ./outputs/train_bkg_data_sideBands_lowQ_cicd.root --outdir ./outputs --ntree 100 --no_plot
  artifacts:
    paths:
      - outputs/

measure_test:
  stage: measure
  image: python:3.8-slim-bullseye
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python measure_bdt.py  --fromdir ./outputs/cicd_test --measurefile ./outputs/measurement_bdt_cicd.root --label cicd_test
  artifacts:
    paths:
      - outputs/
