stages:
  - test_data_inputs

prepare_data_inputs_test:
  stage: test_data_inputs
  image: python:3.8-slim-bullseye
  before_script:
    - apt-get update && apt-get install -y wget
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - wget http://www-hep.colorado.edu/~nzipper/cicd_files/test_data_ntuple.root
  script:
    - python prepare_data_inputs.py -m split -o . -i test_data_ntuple.root
  artifacts:
    paths:
      - output/
